### ISSUE TITLE
Skiko dependencies versions are incompatible.

### ISSUE THREAD

**Issue by PhilippNowak96** [dshatz/pdfmp#44]
After upgrading compose multiplatform to 1.11.0 in my app to fix a textfield related bug, the following warning is appearing during iOS build:

```
w: Skiko dependencies' versions are incompatible.
    io.coil-kt.coil3:coil-core-iosarm64:3.4.0
    \--- org.jetbrains.skiko:skiko:0.9.22.2 -> 0.144.6

    com.dshatz.pdfmp:pdfmp-iosarm64:1.0.12
    \--- org.jetbrains.skiko:skiko:0.9.22.2 -> 0.144.6

This may lead to compilation errors or unexpected behavior at runtime.
Such version mismatch might be caused by dependency constraints in one of the included libraries.
You can inspect resulted dependencies tree via `./gradlew :composeApp:dependencies  --configuration iosArm64CompileKlibraries`.
See more details in Gradle documentation: https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html#sec:listing-dependencies

Note: Skiko is considered implementation detail in Compose Multiplatform and might be incompatible across versions.
Please align Skiko dependencies to the same version. If possible, avoid direct Skiko references and use Compose APIs instead.
```

Also note the hint regarding `coil` as well, therefore see: https://github.com/coil-kt/coil/issues/3382

Looks like everything is still working on my end, so not sure how serious this warning actually is but would be nice to align to get rid of the warning and be on the safe side.

**Comment by dshatz** [comment]
I'm keeping it at `0.9.22.2` for the time being. Skiko API used in pdfmp is very very minimal, compared to the massive usage in compose multiplatform. So it's safe to let skiko be bumped to whatever compose requires in the consuming projects. 

It is also not possible to update to `0.144.6` without updating compose to `1.11.0`.
Updating to compose `1.11.0` is not an option at this point for this project as it [removes x64 apple](https://kotlinlang.org/docs/multiplatform/whats-new-compose-111.html#changes-to-ios-target-support). I don't buy apple products and rely on x64 for testing.
